version: '3.9'
services:
  db:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dating-mobile-app-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
    driver: local
